const menu = [
    {
      id: 1,
      title: 'God of War',
      category: "action",
      price: 15.99,
      img: './images/item-1.jpg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: 'Devil May Cry',
      category: "action",
      price: 15.99,
      img: './images/item-2.jpg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 3,
      title: 'Read Dead Redumption',
      category: "action",
      price: 15.99,
      img: './images/item-3.png',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 4,
      title: 'Death Loop',
      category: "action",
      price: 15.99,
      img: './images/item-4.jpg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 5,
      title: 'Ghost of Tsushmia',
      category: "action",
      price: 15.99,
      img: './images/item-5.jpg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 6,
      title: 'Max-Payne',
      category: "action",
      price: 15.99,
      img: './images/item-6.png',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },

/// adventure

    {
      id: 7,
      title: 'Night in the woods',
      category: 'adventure',
      price: 13.99,
      img: './images/item-7.jpg',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 8,
      title: 'The walking Dead',
      category: 'adventure',
      price: 13.99,
      img: './images/item-8.png',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 9,
      title: 'Life is Strange',
      category: 'adventure',
      price: 13.99,
      img: './images/item-9.jpg',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 10,
      title: 'Minecraft',
      category: 'adventure',
      price: 13.99,
      img: './images/item-10.webp',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 11,
      title: 'The Witcher',
      category: 'adventure',
      price: 13.99,
      img: './images/item-11.jpg',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 12,
      title: '80 Days',
      category: 'adventure',
      price: 13.99,
      img: './images/item-11.png',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },

/// action-adevnture

    {
      id: 13,
      title: 'Batman-arkham asylum',
      category: 'action-adevnture',
      price: 6.99,
      img: './images/item-12.jpg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 14,
      title: 'Tomb-Raider',
      category: 'action-adevnture',
      price: 6.99,
      img: './images/item-13.png',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 15,
      title: 'GTA 5',
      category: 'action-adevnture',
      price: 6.99,
      img: './images/item-14.png',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 16,
      title: 'Control',
      category: 'action-adevnture',
      price: 6.99,
      img: './images/item-15.jpeg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 17,
      title: 'Horizon Zero Down',
      category: 'action-adevnture',
      price: 6.99,
      img: './images/item-17.jpg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 18,
      title: 'The last of US',
      category: 'action-adevnture',
      price: 6.99,
      img: './images/item-18.jpg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    /// android
    {
      id: 19,
      title: 'Among Us',
      category: "Android",
      price: 20.99,
      img: './images/item-19.jpg',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 20,
      title: 'Call of Duty',
      category: "Android",
      price: 20.99,
      img: './images/item-20.png',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 21,
      title: 'PUBG Mobile',
      category: "Android",
      price: 20.99,
      img: './images/item-21.png',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 22,
      title: 'Asphalt 9:Legends',
      category: "Android",
      price: 20.99,
      img: './images/item-22.png',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 23,
      title: 'Need For Speed',
      category: "Android",
      price: 20.99,
      img: './images/item-23.webp',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 24,
      title: 'Garena Free Fire',
      category: "Android",
      price: 20.99,
      img: './images/item-24.png',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    

//// Battle Ground 

    {
      id: 25,
      title: 'Call of Duty:Warzone',
      category: "Battle Royale",
      price: 20.99,
      img: './images/item-25.jpg',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 26,
      title: 'PlayerUnknown Battlegrounds',
      category: "Battle Royale",
      price: 20.99,
      img: './images/item-26.png',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 27,
      title: 'Apex Legends',
      category: "Battle Royale",
      price: 20.99,
      img: './images/item-27.png',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 28,
      title: 'Fortnite',
      category: "Battle Royale",
      price: 20.99,
      img: './images/item-28.jpg',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 29,
      title: 'Valorant',
      category: "Battle Royale",
      price: 20.99,
      img: './images/item-29.png',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 30,
      title: 'Counter-Strike',
      category: "Battle Royale",
      price: 20.99,
      img: './images/item-30.jpg',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    
  ];
  export default menu;